
spring:
  application:
    name: jumbo
  datasource:
    url: jdbc:mysql://localhost:3306/jumbo?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    timeout: 60000
server:
  servlet:
    context-path: /jumbo
  port: 8080
logging:
  level:
    root: INFO
